export const data = [
  {
    id: 1,
    title: 'Order ID #1234',
    date: 'September 16, 2024',
    time: '1:00 am',
    amount: 55,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 2,
    title: 'Order ID #1233',
    date: 'September 15, 2024',
    time: '2:00 pm',
    amount: 32,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 3,
    title: 'Order ID #1232',
    date: 'September 14, 2024',
    time: '11:05 pm',
    amount: 69,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 4,
    title: 'Order ID #1231',
    date: 'September 12, 2024',
    time: '9:00 pm',
    amount: 100.51,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 5,
    title: 'Order ID #1230',
    date: 'September 10, 2024',
    time: '10:30 am',
    amount: 45,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 6,
    title: 'Order ID #1229',
    date: 'September 8, 2024',
    time: '8:45 pm',
    amount: 77.25,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 7,
    title: 'Order ID #1228',
    date: 'September 7, 2024',
    time: '4:15 pm',
    amount: 54.99,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 8,
    title: 'Order ID #1227',
    date: 'September 5, 2024',
    time: '3:00 pm',
    amount: 120.75,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 9,
    title: 'Order ID #1228',
    date: 'September 7, 2024',
    time: '4:15 pm',
    amount: 54.99,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 10,
    title: 'Order ID #1227',
    date: 'September 5, 2024',
    time: '3:00 pm',
    amount: 120.75,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 11,
    title: 'Order ID #1228',
    date: 'September 7, 2024',
    time: '4:15 pm',
    amount: 54.99,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
  {
    id: 12,
    title: 'Order ID #1227',
    date: 'September 5, 2024',
    time: '3:00 pm',
    amount: 120.75,
    location: 'Chowking Florida',
    paymentType: 'Visa',
  },
];
